name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  # Create release from data MDD.zip
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: assets/data/MDD.zip
          asset_name: MDD.zip
          tag: ${{ github.ref }}
